version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=next-saas
    volumes:
      - next_saas_postgres_data:/bitnami/postgresql

volumes:
  next_saas_postgres_data:
    driver: local